### ISSUE TITLE
tracker question

### ISSUE THREAD

**Issue by Alan-Py** [lucidrains/med-seg-diff-pytorch#15]
when I use 4 GPU in accelerator config.The tracker has the following problems in driver.py:

![eca6bb4525063bb884b10b36682fefb](https://user-images.githubusercontent.com/56969590/232277017-f05d6188-4f48-4dc3-b571-e75db8b336d2.png)
--------------->>>>
```python
for tracker in accelerator.trackers:
```
But when i use 1 GPU，I solve this error.
Can someone help me to solve this problem?
@isamu-isozaki

**Comment by Alan-Py** [comment]
Maybe I solve this problem by use ``if accelerator.is_main_process``to judge

**Comment by Alan-Py** [comment]
> Maybe I solve this problem by useing `if accelerator.is_main_process`to judge

its not work

**Comment by Alan-Py** [comment]
My accelerate env is 
```shell

- `Accelerate` version: 0.16.0
- Platform: Linux-4.15.0-142-generic-x86_64-with-glibc2.23
- Python version: 3.9.16
- Numpy version: 1.23.5
- PyTorch version (GPU?): 1.10.1+cu111 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - dynamo_backend: NO
        - num_processes: 4
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: no
```

**Comment by isamu-isozaki** [comment]
@Alan-Py thanks for the issue, and haha totally forgot about distributed stuff. You can do
```
if self.accelerator.sync_gradients and self.is_main:
```
on line 161 and indent everything and I think it'll work. Feel free to make a pr on this too! I think @lucidrains will like it

**Comment by Alan-Py** [comment]
OK，I‘ll try it. Thank for your good job.

**Comment by Alan-Py** [comment]
![image](https://user-images.githubusercontent.com/56969590/232372334-0c133140-d033-4e0e-93b6-ecf513179467.png)

Solve this problem!!! Thank you @isamu-isozaki
