### ISSUE TITLE
Performance of Transformer Addition

### ISSUE THREAD

**Issue by LLYX** [lucidrains/med-seg-diff-pytorch#8]
In the follow up paper MedSegDiff-V2, the authors mention that:

"A natural next step is to combine the transformer-based UNet, such as TransUNet, with DPM. However, we found that this straightforward strategy leads to subpar performance. One issue is that the transformer-abstracted conditional feature is not compatible with the feature of the backbone. The transformer learns deep semantic features from the raw image, while the diffusion backbone abstracts features from a corrupted, noisy mask. Additionally, the dynamic and global nature of the transformer makes it more sensitive than CNNs. Thus, the adaptive condition strategy used in MedSegDiff causes larger variance in the outputs in the transformer setting. This requires running the model more times for ensemble and makes it harder to converge during training."

Have you found any additional difficulties/performance drops using the Transformer simply as an additional component in the middle of the UNet?

Also, do you have any plans to implement MedSegDiff-V2?

Thanks again for another cool implementation that helped me understand the original paper!

**Comment by lucidrains** [comment]
@LLYX i would not bet against it.. https://arxiv.org/abs/2301.11093
